package kotlin

import (
	"fmt"
	"path/filepath"
	"strings"

	"github.com/antigravity/kogen/internal/core/domain"
)

func generateMigrations(doc *domain.DBMLDocument, spec *domain.GeneratorSpec) ([]domain.GeneratedFile, error) {
	var files []domain.GeneratedFile

	var ddlStatements []string

	// Enums (for Postgres)
	if spec.Database == domain.DBPostgreSQL {
		for _, enumObj := range doc.Enums {
			var vals []string
			for _, v := range enumObj.Values {
				vals = append(vals, fmt.Sprintf("'%s'", v.Name))
			}
			ddlStatements = append(ddlStatements, fmt.Sprintf("CREATE TYPE %s AS ENUM (%s);", enumObj.FullName(), strings.Join(vals, ", ")))
		}
	}

	// Tables
	for _, tbl := range doc.Tables {
		var colDefs []string
		for _, c := range tbl.Columns {
			sqlType := MapDBMLTypeToSQL(c, spec.Database)
			nullability := "NOT NULL"
			if c.Nullable {
				nullability = "NULL"
			}
			if c.PK && spec.Database != domain.DBSQLite {
				nullability += " PRIMARY KEY"
			}
			if c.Unique {
				nullability += " UNIQUE"
			}
			if c.DefaultVal != "" {
				nullability += fmt.Sprintf(" DEFAULT %s", c.DefaultVal)
			}
			colDefs = append(colDefs, fmt.Sprintf("    %s %s %s", c.Name, sqlType, nullability))
		}

		ddlStatements = append(ddlStatements, fmt.Sprintf("CREATE TABLE IF NOT EXISTS %s (\n%s\n);", tbl.FullName(), strings.Join(colDefs, ",\n")))

		// Indexes
		for _, idx := range tbl.Indexes {
			idxName := idx.Name
			if idxName == "" {
				idxName = fmt.Sprintf("idx_%s_%s", tbl.Name, strings.Join(idx.Columns, "_"))
			}
			uniqStr := ""
			if idx.Unique {
				uniqStr = "UNIQUE "
			}
			ddlStatements = append(ddlStatements, fmt.Sprintf("CREATE %sINDEX IF NOT EXISTS %s ON %s (%s);", uniqStr, idxName, tbl.FullName(), strings.Join(idx.Columns, ", ")))
		}
	}

	// Foreign Key Refs
	for _, ref := range doc.Refs {
		if len(ref.SourceColumns) > 0 && len(ref.TargetColumns) > 0 {
			ddlStatements = append(ddlStatements, fmt.Sprintf("ALTER TABLE %s ADD CONSTRAINT %s FOREIGN KEY (%s) REFERENCES %s (%s);",
				ref.SourceFullName(),
				func() string {
					if ref.Name != "" {
						return ref.Name
					}
					return fmt.Sprintf("fk_%s_%s", ref.SourceTable, ref.TargetTable)
				}(),
				strings.Join(ref.SourceColumns, ", "),
				ref.TargetFullName(),
				strings.Join(ref.TargetColumns, ", ")))
		}
	}

	sqlContent := fmt.Sprintf("-- Database Initial DDL Script for %s (%s)\n-- Generated by kogen CLI\n\n%s\n",
		spec.ProjectName, string(spec.Database), strings.Join(ddlStatements, "\n\n"))

	filePath := filepath.Join("src/main/resources/db/migration", "V1__init_schema.sql")
	files = append(files, domain.GeneratedFile{Path: filePath, Content: sqlContent})

	return files, nil
}
