package kotlin

import (
	"fmt"
	"path/filepath"
	"strings"

	"github.com/antigravity/kogen/internal/core/domain"
)

func generateOpenAPISpec(doc *domain.DBMLDocument, spec *domain.GeneratorSpec) ([]domain.GeneratedFile, error) {
	var files []domain.GeneratedFile
	projectName := spec.ProjectName
	if doc.Project != nil && doc.Project.Name != "" {
		projectName = doc.Project.Name
	}

	var pathBlocks []string
	var schemaBlocks []string

	for _, tbl := range doc.Tables {
		entityName := ToPascalCase(tbl.Name)
		kebabName := ToKebabCase(tbl.Name)
		pkCol := GetPKColumn(tbl)
		pkType := strings.ToLower(pkCol.Type)

		// Schema fields
		var propDecls []string
		var createProps []string

		for _, c := range tbl.Columns {
			prop := ToCamelCase(c.Name)
			yamlType := "string"
			switch strings.ToLower(c.Type) {
			case "int", "integer", "int4", "smallint":
				yamlType = "integer"
			case "bigint", "long":
				yamlType = "integer"
			case "boolean", "bool":
				yamlType = "boolean"
			case "decimal", "numeric", "float", "double":
				yamlType = "number"
			}

			propDecls = append(propDecls, fmt.Sprintf(`        %s:
          type: %s
          description: "%s"`, prop, yamlType, c.Note))

			if !c.PK && !c.Increment {
				createProps = append(createProps, fmt.Sprintf(`        %s:
          type: %s`, prop, yamlType))
			}
		}

		schemaBlocks = append(schemaBlocks, fmt.Sprintf(`    %sResponse:
      type: object
      properties:
%s

    Create%sRequest:
      type: object
      properties:
%s`, entityName, strings.Join(propDecls, "\n"), entityName, strings.Join(createProps, "\n")))

		// OpenAPI Paths for entity
		pathBlocks = append(pathBlocks, fmt.Sprintf(`  /api/v1/%s:
    get:
      summary: List all %s items
      tags: [%s]
      parameters:
        - name: page
          in: query
          schema: { type: integer, default: 1 }
        - name: size
          in: query
          schema: { type: integer, default: 20 }
      responses:
        '200':
          description: OK
    post:
      summary: Create new %s
      tags: [%s]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Create%sRequest'
      responses:
        '201':
          description: Created

  /api/v1/%s/{id}:
    get:
      summary: Get %s by ID
      tags: [%s]
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: %s }
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
    put:
      summary: Update %s by ID
      tags: [%s]
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: %s }
      responses:
        '200':
          description: OK
    delete:
      summary: Delete %s by ID
      tags: [%s]
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: %s }
      responses:
        '204':
          description: No Content`, kebabName, entityName, entityName, entityName, entityName, entityName, kebabName, entityName, entityName, pkType, entityName, entityName, pkType, entityName, entityName, pkType))
	}

	openapiYaml := fmt.Sprintf(`openapi: 3.0.3
info:
  title: %s REST API
  description: Native Kotlin Hexagonal REST API Backend generated by kogen CLI.
  version: 1.0.0
servers:
  - url: http://localhost:%d
    description: Local Environment
paths:
%s

components:
  schemas:
%s
`, projectName, spec.ServerPort, strings.Join(pathBlocks, "\n\n"), strings.Join(schemaBlocks, "\n\n"))

	filePath := filepath.Join("docs", "openapi.yaml")
	files = append(files, domain.GeneratedFile{Path: filePath, Content: openapiYaml})

	return files, nil
}
